# Numpy library

In [3]:
import numpy as np

In [4]:
# 1D Array (Vetcor)
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
# 2D array (Matrix)
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [6]:
# .shape : RETURN DIMANTION
print(a.shape,b.shape)

(4,) (2, 2)


In [7]:
# RESHAPE() : CHNAGE DIMANTION
c = a.reshape((4,-1))
c.shape

(4, 1)

In [8]:
# 3D array (Tebsor)
d = a.reshape((2,2,1))
d.shape

(2, 2, 1)

In [9]:
# np.concatinate()
a = np.array([1,2])
b = np.array([3,4])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4])

In [10]:
# math
a = np.array([1,2,3])
b = np.array([2,3,4])
c = a + b
c

array([3, 5, 7])

In [11]:
# broadcasting
d = a + 1
d

array([2, 3, 4])

In [12]:
a = np.array([1,2,3,4,5])
a = a.flatten()

# slice [start:end:step]
b = a[1:4:1]
b

array([2, 3, 4])

In [13]:
# for a > 3
c = a[a>=3]
c

array([3, 4, 5])

In [14]:
# slice
print(a[1:4:1])
print(a[a>3])
# sum of all elemnts
sum = np.sum(a)
print(sum)
# min and max
max = np.max(a)
print(max)
# sort np.sort

[2 3 4]
[4 5]
15
5


In [15]:
# random
b = np.random.randint(0,1,(3,5))
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [16]:
# stack on top (v/h)
stack = np.vstack((a,b))
stack

array([[1, 2, 3, 4, 5],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# Z-Score Normalization (Standardization)
mean = np.mean(a)
std = np.std(a)
norm = (a-mean)/std
norm

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])